BIN := "./bin/apartments"

build:
	go build -v -o $(BIN) ./cmd

run:
	docker compose -f deploy/docker-compose.yaml up

down:
	docker compose -f deploy/docker-compose.yaml down

dbup:
	docker compose -f deploy/docker-compose-unit-test.yaml up -d

test: dbup
	go test -race -count 3 ./internal/...
	docker compose -f deploy/docker-compose-unit-test.yaml down

install-lint-deps:
	(which golangci-lint > /dev/null) || curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(shell go env GOPATH)/bin v1.57.2

lint: install-lint-deps
	golangci-lint run ./...

.PHONY: build run test lint