services:
  psql:
    image: postgres:16.4-alpine3.20
    container_name: apartmentsdb
    ports:
      - 5433:5432
    env_file:
      ../.env
    volumes: 
    - ../internal/storage/migrations/:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev -d apartmentsdb"]
      interval: 5s
      timeout: 2s
      retries: 2
    networks:
      - app-network

  apartments:
    build:
     context: ../.
     dockerfile: ./build/dockerfile
    container_name: apartments
    ports:
       - 8000:8000
    restart: unless-stopped
    env_file: 
      ../.env
    depends_on:
     - psql
    networks:
      - app-network

networks:
 app-network:
  driver: bridge