services:
  psql:
    image: postgres:16.4-alpine3.20
    container_name: apartmentsdb
    ports:
      - 5433:5432
    expose:
      - 5433
    env_file:
      ../.env
    volumes: 
    - ../internal/storage/migrations/:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev -d apartmentsdb"]
      interval: 5s
      timeout: 2s
      retries: 2
    networks:
      - tests

networks:
  tests:
      driver: bridge