services:
   psql:
    image: postgres:16.4-alpine3.20
    container_name: apartmentsdb
    ports:
      - 5433:5432
    env_file: ../test.env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes: 
    - ../internal/storage/migrations/:/docker-entrypoint-initdb.d
    - apartmentsdb-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev -d apartmentsdb"]
      interval: 5s
      timeout: 2s
      retries: 2
    networks:
      - app

   apartments:
     build:
       context: ../.
       dockerfile: ./build/dockerfile
     container_name: apartments
     ports:
      - 8000:80
     restart: unless-stopped
     env_file: ../test.env
     depends_on:
      - psql
     networks:
      - app

   nginx:
     image: nginx:latest
     container_name: nginx
     ports:
     - 80:80
     environment:      
     - NGINX_PORT=80
     volumes:
     - ../build/tmpl:/etc/nginx/templates
     networks:
     - app

   tests:
     image: golang:1.22.5-alpine3.20
     volumes:
     - ./../:/app/
     working_dir: /app
     command: sh -c 'go test -v ./tests/...'
     environment:
      CGO_ENABLED: 0
     depends_on:
     - psql
     - apartments
     - nginx
     networks:
     - app

volumes:
  apartmentsdb-data:

networks:
  app:
   driver: bridge